#' Balance a dataset using the ROSE algorithm
#' 
#' The data sharing labels in PMC from 2018 are heavily imbalanced.
#' Most of the documents either have no data sharing information or
#' supplementary material (labels 0 and 1 from the `label_DAS` function).
#' This function applies the Random Over-Sampling Experiment (ROSE) algorithm
#' to generate synethically oversampled datapoints of groups 2 through 6. 
#'
#' @param das_df A full data matrix, with labels and input features.
#' @param p The probability of the minority class examples in the 
#' resulting data set generated by ROSE. p should be between 0 and 1.
#' 
#' @return A resampled dataset, with balanced labels.
#' 
#' @examples 
#' balanced_data <- balance_labels(my_data, p = 0.6)
#' 
#' @importFrom magrittr "%>%"
#' @importFrom ROSE "ROSE"
#' 
#' @export

balance_labels <- function(das_df, p) {
  
  split_classes <- function(df, class) {
    df %>% 
      dplyr::filter(label == 0 | label == class) %>% 
      dplyr::mutate(label = factor(label))
  }
  
  class2 <- 
    ROSE::ROSE(
      formula = label ~ .,
      data = split_classes(das_df, 2),
      p = p,
      seed = 128
    )
  
  class3 <- 
    ROSE::ROSE(
      formula = label ~ .,
      data = split_classes(das_df, 3),
      p = p,
      seed = 128
    )
  
  class4 <- 
    ROSE::ROSE(
      formula = label ~ .,
      data = split_classes(das_df, 4),
      p = p,
      seed = 128
    )
  
  class5 <- 
    ROSE::ROSE(
      formula = label ~ .,
      data = split_classes(das_df, 5),
      p = p,
      seed = 128
    )
  
  class6 <- 
    ROSE::ROSE(
      formula = label ~ .,
      data = split_classes(das_df, 6),
      p = p,
      seed = 128
    )
  
  dplyr::bind_rows(
    dplyr::filter(das_df, label == 1),
    tibble::as_tibble(class2$data),
    tibble::as_tibble(class3$data),
    tibble::as_tibble(class4$data),
    tibble::as_tibble(class5$data),
    tibble::as_tibble(class6$data)
  )
  
}