#' Clean DAS information created by the `get_DAS` function
#' 
#' This function cleans and preps data sharing information to use 
#' to later label the PMCIDs by data sharing type.
#'
#' @param das_df A tibble generated by `get_DAS`
#' 
#' @return A tibble with the columns PMCID, tagging_method, content, 
#' has_das, and attached_media. This resulting tibble is ready to be passed 
#' into the function `label_DAS`.
#' 
#' @examples 
#' get_DAS("PMC3257301") %>% 
#' clean_DAS()
#' 
#' @importFrom magrittr "%>%"
#' 
#' @export

clean_DAS <- function(das_df) {
  das_df %>% 
    dplyr::mutate(
      has_das = (das != "No data availability information.")
    ) %>% 
    tidyr::unnest(das) %>% 
    dplyr::mutate(
      attached_media = dplyr::if_else(
        tagging_method == "Supplementary Materials" & 
          stringr::str_detect(content, "<media"),
        stringr::str_extract(content, "<media.+>"),
        NA_character_
      ),
      content = dplyr::if_else(
        stringr::str_detect(content, "<media"), 
        stringr::str_remove(content, "<media.+>"),
        content
      )
    ) %>% 
    dplyr::mutate(
      attached_media = stringr::str_extract(
        attached_media, 
        "(?<=href=\".{1,200}\\.)(\\w|\\d){1,5}(?=\")"
      )
    )%>% 
    dplyr::select(PMCID, has_das, tagging_method, content, attached_media) %>% 
    dplyr::mutate(
      attached_media = dplyr::case_when(
        stringr::str_detect(content, ".pdf") ~ "pdf",
        stringr::str_detect(content, ".cif") ~ "cif",
        TRUE ~ attached_media
      ),
      content = dplyr::case_when(
        stringr::str_detect(content, ".pdf") ~ str_extract(content, "(?<=<p>).+(?=</p>)"),
        stringr::str_detect(content, ".cif") ~ str_extract(content, "(?<=<p>).+(?=</p>)"),
        TRUE ~ content
      ),
      content = stringr::str_remove_all(content, "\t|\n|<.{1,20}>") %>% 
        stringr::str_squish() %>% 
        stringr::str_replace_all("([:lower:](?=[:upper:]))", "\\1 ") %>% 
        stringr::str_remove_all("[:digit:]*")
    )
}