#' Data availability information of PMC documents
#'
#' A dataset containing the PMCID of documents published from
#' January 2017 to December 2019, with data sharing information nested
#' as tibbles. The data sharing information is either a tibble with
#' tagging method and content, or a string saying "No data availability
#' information."
#'
#' @format A data frame with 94114 rows and 5 variables:
#' \describe{
#'   \item{month}{month of publication}
#'   \item{year}{year of publication}
#'   \item{PMCID}{unique 7-digit ID associated with document}
#'   \item{das}{a nested tibble with data sharing information}
#'   \item{has_das}{logical value for a document having any data sharing information}
#'   ...
#' }
"all_das"


#' Data availability labels of PMC documents
#'
#' A dataset containing the PMCID of documents published from
#' January 2017 to December 2019, with a integer label between
#' 0 and 8 that categorizes the data sharing of a document into 
#' one of the 9 groups. The groups are as follows: 
#' 
#'   0) No data sharing information.
#'   1) Supplementary materials for download.
#'   2) Data citation or link to repository.
#'   3) Data upon request.
#'   4) Restricted access.
#'   5) Supplementary materials, but no downloadable file.
#'   6) Other.
#'   7) Inline figures or tables.
#'   8) Two or more categories.
#'   
#' The groups were generated by passing the `all_das` dataset into
#' the label_DAS function in the package. 
#'
#' @format A data frame with 94114 rows and 4 variables:
#' \describe{
#'   \item{month}{month of publication}
#'   \item{year}{year of publication}
#'   \item{PMCID}{unique 7-digit ID associated with document}
#'   \item{label}{an integer from 0 to 8 describing the data sharing}
#'   ...
#' }
"all_labeled_das"


#' All words contained in the data availability section of a document
#'
#' A dataset containing all the words in data availability section of
#' documents published between January 2017 and December 2019. During the tagging
#' process, sections of documents are pulled out that are related to data sharing,
#' whether it be an actual Data Availability Statement or an inline figure. 
#' The text content of these sections is made available in this dataset.
#'
#' @format A data frame with 19930498 rows and 2 variables:
#' \describe{
#'   \item{PMCID}{unique 7-digit ID associated with document}
#'   \item{word}{an English word that appears in the document's data section}
#'   ...
#' }
"das_words"


#' MeSH terms by number, with paths in the tree structure
#'
#' A dataset containing all the MeSH terms and their associated numbers.
#' MeSH terms are numbered using a tree, and this dataset provides the
#' different levels of the tree associated with a term. This dataset was
#' created from \url{https://www.nlm.nih.gov/databases/download/mesh.html}.
#'
#' @format A data frame with 60666 rows and 10 variables:
#' \describe{
#'   \item{node1}{first level of the tree, a letter between A and Z, followed by a numerical value}
#'   \item{node2}{second level of the tree, a three digit number. For nodes 2 through 8, NA if further down the tree than the MeSH term.}
#'   \item{node3}{third level of the tree, a three digit number}
#'   \item{node4}{fourth level of the tree, a three digit number}
#'   \item{node5}{fifth level of the tree, a three digit number}
#'   \item{node6}{sixth level of the tree, a three digit number}
#'   \item{node7}{seventh level of the tree, a three digit number}
#'   \item{node8}{eighth level of the tree, a three digit number}
#'   \item{description}{the MeSH term}
#'   \item{pathString}{a path of nodes 1 through 8}
#'   ...
#' }
"mesh_table"


#' The highest level MeSH terms with associated the first level of the MeSH tree
#'
#' A dataset containing only the highest level MeSH terms, with the
#' associated branch number. 
#'
#' @format A data frame with 111 rows and 2 variables:
#' \describe{
#'   \item{descriptor}{the MeSH term}
#'   \item{branch}{the branch number containing a letter A through Z, followed by a two digit number}
#'   ...
#' }
"mesh_top_level"