#' Generate numeric features from text data to use in modeling
#' 
#' This function generates features depending on the input mode, to 
#' embed text data as numeric features. This function also serves as
#' a general preprocessing step that tokenizes the text, removes 
#' stopwords, and either lemmatizes or stems the words (depending on input).
#'
#' @param df A tibble with two columns: PMCID and text generated by 
#' `tidypmc::pmc_text`.
#' @param lem_stem A string that is one of "lem" or "stem" which tells
#' the function to respectively lemmatize or stem the words
#' @param mode A string that is one of: 'bow', 'tfidf', or 'tm n' where 
#' n is an integer number. The 'bow' mode creates a document-term matrix
#' with counts. The 'tfidf' mode creates a document-term matrix with 
#' term frequency inverse document frequency values. The 'tm n' mode
#' creates a matrix with topic modeling embeddings, generated by an
#' unsupervised Latent Dirichlet allocation algorithm. n is an integer value
#' that specifies the number of topics that we use in the LDA model. In this 
#' mode, each row is a document and each column is a topic model feature.
#' 
#' @return A document-term matrix if mode is "bow" or "tfidf" or a matrix with
#' LDA topic model features if mode is "tm n".
#' 
#' @examples 
#' input_df <-
#' tribble(
#'    ~PMCID, ~xml,
#'    "PMC3257301", xml_by_id("PMC3257301")
#' ) %>% 
#' mutate(
#'    text = pmc_text(xml)
#' ) %>% 
#' select(PMCID, text)
#' 
#' generate_features(input_df, lem_stem = "lem", mode = "tm 10")
#' generate_features(input_df, lem_stem = "lem", mode = "tfidf")
#' generate_features(input_df, lem_stem = "stem", mode = "bow")
#' 
#' @importFrom magrittr "%>%"
#' 
#' @export

generate_features <- function(df, lem_stem, mode) {
  
  clean_df <- 
    df %>% 
    tidyr::unnest(text) %>% 
    dplyr::mutate(text = textclean::replace_contraction(text)) %>% 
    dplyr::select(PMCID, text) %>% 
    tidytext::unnest_tokens(word, text) %>% 
    dplyr::anti_join(tidytext::stop_words, by = 'word') %>% 
    dplyr::mutate(
      word = word %>% 
        stringr::str_to_lower() %>% 
        stringr::str_trim() %>% 
        stringi::stri_trans_general("Latin-ASCII")
    ) %>% 
    dplyr::filter(!stringr::str_detect(word, "\\d")) %>% 
    dplyr::filter(!stringr::str_detect(word, "[^a-z]")) %>% 
    dplyr::mutate(
      word = dplyr::case_when(
        lem_stem == "lem" ~ textstem::lemmatize_words(word),
        lem_stem == "stem" ~ textstem::stem_words(word),
        TRUE ~ word
      )
    )
  
  if (mode == "bow") {
    
    clean_df %>% 
      dplyr::count(PMCID, word) %>% 
      tidytext::cast_dtm(
        document = PMCID, 
        term = word, 
        value = n,
        weighting = tm::weightTf
      )
    
  } else if (mode == "tfidf") {
    
    clean_df %>%
      dplyr::count(PMCID, word) %>% 
      tidytext::cast_dtm(
        document = PMCID, 
        term = word, 
        value = n,
        weighting = tm::weightTfIdf
      )
    
  } else if (stringr::str_sub(mode, 1, 2) == "tm") {
    
    n <-
      stringr::str_sub(
        mode, 4, stringr::str_length(mode)
      ) %>% 
      as.integer()
    
    PMCIDs <-
      clean_df %>%
      dplyr::pull(PMCID) %>%
      unique()

    tokens <-
      clean_df %>%
      dplyr::group_by(PMCID) %>%
      dplyr::mutate(
        full_text = str_c(word, sep = "", collapse = " ")
      ) %>%
      dplyr::ungroup() %>%
      dplyr::pull(full_text) %>%
      unique() %>%
      tolower() %>%
      text2vec::word_tokenizer()

    it <-
      text2vec::itoken(tokens, ids = PMCIDs, progressbar = FALSE)

    v <-
      it %>%
      text2vec::create_vocabulary() %>%
      text2vec::prune_vocabulary(term_count_min = 2, doc_proportion_max = 0.5)

    vectorizer <- text2vec::vocab_vectorizer(v)

    dtm <- text2vec::create_dtm(it, vectorizer, type = "dgTMatrix")

    lda_model <-
      text2vec::LDA$new(n_topics = n, doc_topic_prior = 0.1, topic_word_prior = 0.01)

    lda_model$fit_transform(
      x = dtm,
      n_iter = 1000,
      convergence_tol = 0.001,
      n_check_convergence = 25,
      progressbar = FALSE
    )
    
  } else {
    
    stop("Invalid input. Mode must be one of the following: bow, tfidf, or tm n (where n is an integer value).")
    
  }
}