#' Labels documents by data sharing class
#' 
#'   0) No data sharing information.
#'   1) Supplementary materials for download.
#'   2) Data citation or link to repository.
#'   3) Data upon request.
#'   4) Restricted access.
#'   5) Supplementary materials, but no downloadable file.
#'   6) Other.
#'   7) Inline figures or tables.
#'   8) Two or more categories.
#'
#' @param das_df A tibble generated by `get_DAS` and `clean_DAS`
#' 
#' @return A tibble with the columns PMCID and label
#' 
#' @examples 
#' get_DAS("PMC3257301") %>% 
#' clean_DAS() %>% 
#' label_DAS()
#' 
#' @importFrom magrittr "%>%"
#' 
#' @export

label_DAS <- function(das_df) {
  url1 <- "https://www.nlm.nih.gov/NIHbmic/domain_specific_repositories.html"
  table1 <-
    xml2::read_html(url1) %>% 
    rvest::html_table()
  
  url2 <- "https://www.nlm.nih.gov/NIHbmic/other_data_resources.html"
  table2 <-
    xml2::read_html(url2) %>% 
    rvest::html_table()
  
  other_repositories <-
    tribble(
      ~repository_name, ~abbreviation,
      "Dataverse", NA_character_,
      "Dryad", NA_character_,
      "Figshare", NA_character_,
      "Mendeley Data", NA_character_,
      "Open Science Framework", NA_character_,
      "Vivli", NA_character_,
      "Zenodo", NA_character_
    )
  
  get_repository_names <- function(table) {
    table[[1]] %>% 
      transmute(
        repository_name = `Repository Name`
      ) %>% 
      mutate(
        abbreviation = if_else(
          str_detect(repository_name, "\\("),
          str_extract(repository_name, "\\(.+\\)") %>% 
            str_remove("\\(") %>% 
            str_remove("\\)"),
          NA_character_
        ),
        repository_name = str_remove(repository_name, "\\(.+\\)")
      )
  }
  
  repositories <-
    bind_rows(
      get_repository_names(table1),
      get_repository_names(table2),
      other_repositories
    )
  
  full_names_regex <-
    repositories %>%  
    pull(repository_name) %>% 
    str_trim() %>% 
    str_c(collapse = "|")
  
  abbrev_regex <-
    repositories %>%  
    filter(!is.na(abbreviation)) %>% 
    pull(abbreviation) %>%
    str_trim() %>% 
    str_c(collapse = "|")
  
  none_regex <- "(N|n)ot applicable|(N|n)o additional data|(N|n)ot a data-based article"
  
  # 0) No data sharing information.
  # 1) Supplementary materials for download.
  # 2) Data citation or link to repository.
  # 3) Data upon request.
  # 4) Restricted access.
  # 5) Supplementary materials, but no downloadable file.
  # 6) Other.
  # 7) Inline figures or tables.
  # 8) Two or more categories.
  
  das_df %>% 
    mutate(
      label = case_when(
        !has_das | str_detect(content, none_regex) ~ 0L,
        tagging_method == "Supplementary Materials" & !is.na(attached_media) ~ 1L,
        (tagging_method == "Supplementary Materials" & is.na(attached_media)) |
          str_detect(content, "included in") ~ 5L,
        tagging_method == "Data Citations" | 
          str_detect(content, full_names_regex) |
          str_detect(content, abbrev_regex) |
          str_detect(content, "doi|DOI") |
          str_detect(content, "github|GitHub") |
          str_detect(content, "http") ~ 2L, 
        str_detect(content, "request|Request") ~ 3L,
        str_detect(content, "(R|r)estricted|(P|p)rivacy") ~ 4L, 
        tagging_method == "Inline Table" | tagging_method == "Inline Figure" ~ 7L,
        TRUE ~ 6L
      )
    ) %>%
    select(PMCID, label) %>%
    unique() %>% 
    group_by(PMCID) %>%
    mutate(doc_count = n()) %>%
    ungroup() %>%
    mutate(label = if_else(doc_count > 1, 8L, label)) %>%
    select(PMCID, label) %>%
    unique()
}
