#' Normalize and preprocess numeric features
#' 
#' This function normalizes and centers the input matrix (by rows), after we've
#' generated features via the `generate_features` function. There's also
#' the option of performing dimensionality reduction by Principle Component
#' Analysis. 
#'
#' @param mat A matrix (either document-term matrix or topic model matrix) 
#' generated by `generate_features`
#' @param mode A string that either has the value 'pca n' or 'none' where
#' n is an integer number specifying the number of principle components
#' from the principle component decomposition.
#' @param type A string that is either 'dtm' or 'none'. type should be 'dtm'
#' if we generated a document-term matrix in `generate_features` (from bow
#' or tfidf) and 'none' if we generated a topic model matrix. 
#' 
#' @return A normalized and centered feature matrix, with possible dimensionality
#' reduction if mode = 'pca n'. If mode = 'pca n', the function will also print the
#' principle component information. 
#' 
#' @examples 
#' input_mat <-
#' tribble(
#'    ~PMCID, ~xml,
#'    "PMC3257301", xml_by_id("PMC3257301")
#' ) %>% 
#' mutate(
#'    text = pmc_text(xml)
#' ) %>% 
#' select(PMCID, text) %>% 
#' generate_features(input_df, lem_stem = "lem", mode = "tfidf")
#' 
#' preprocess_text(input_mat, mode = "none", type = "dtm")
#' preprocess_text(input_mat, mode = "pca 50", type = "dtm")
#' 
#' @importFrom magrittr "%>%"
#' 
#' @export

preprocess_text <- function(mat, mode, type) {
  
  if (type == "dtm"){
    print("Normalizing a (sparse) Document Term Matrix")
    
    mat_norm_dtm <-
      mat %>% 
      group_by(document) %>% 
      mutate(
        count = count - mean(count), # center / subtract mean
        count = if_else(
          count == 0,
          0,
          count / sqrt(sum(count**2)) # normalize
        )
      ) %>% 
      ungroup() %>% 
      cast_dtm(document, term, count)
    
    mat_norm <-
      sparseMatrix(
        i = mat_norm_dtm$i,
        j = mat_norm_dtm$j,
        x = mat_norm_dtm$v,
        dim = dim(mat_norm_dtm),
        dimnames = dimnames(mat_norm_dtm)
      )
    
  } else {
    print("Normalizing a dense matrix")
    
    mat_demean <-
      mat - rowMeans(mat)

    # normalize rows (documents)
    mat_norm <-
      mat_demean %>%
      wordspace::normalize.rows(method = "euclidean")
  }
    
  if (stringr::str_sub(mode, 1, 3) == "pca") {
    
    print("Performing dimensionality reduction by PCA")
    
    n <-
      stringr::str_sub(
        mode, 5, stringr::str_length(mode)
      ) %>%
      as.integer()
    
    eig_decomp <-
      mat_norm %>%
      irlba::prcomp_irlba(n = n)
    
    print(summary(eig_decomp)) 
    
    eig_decomp$x
    
  } else {
    
    mat_norm
    
  }
}